#! /usr/bin/env bash
set -e

type nodejs


source config

if ! [[ $site ]]
then
  site=.
  echo '$site not set in config. Assuming files are destined to the current directory'
fi

for name in "${names[@]}"
do
  dest=${site}
  theme=node_modules/jsonresume-theme-kendall
  if hackmyresume BUILD jrs/${name}.json TO ${dest}/${name}/index.html --theme ${theme}
  then
    echo HTML
  fi
  theme=node_modules/jsonresume-theme-onepage
  if hackmyresume BUILD jrs/${name}.json TO ${dest}/${name}/print/index.html --theme ${theme}
  then
    echo 'PRINT (html)'
    make -B ${dest}/${name}/${name}.docx
  fi
done

read -p "Push to server for site ${site} [YyNn]> "
case $REPLY in
	Y|y)
	  echo Pushing to ${site}
	  ./push
	  ;;
	N|n) exit 0 ;;
	*) echo Not pushing to ${site} ;;
esac
